/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tControlMotors_template.c => src/tControlMotors.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port: cLeftMotor signature: sMotor context:task
 *   ER             cLeftMotor_setPower( int power );
 *   void           cLeftMotor_initializePort( int32_t type );
 * call port: cRightMotor signature: sMotor context:task
 *   ER             cRightMotor_setPower( int power );
 *   void           cRightMotor_initializePort( int32_t type );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tControlMotors_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eControlMotors
 * entry port: eControlMotors
 * signature:  sControlMotors
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eControlMotors_steer
 * name:         eControlMotors_steer
 * global_name:  tControlMotors_eControlMotors_steer
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eControlMotors_steer(int power, int turn_ratio)
{
	cLeftMotor_initializePort( LARGE_MOTOR );
	cRightMotor_initializePort( LARGE_MOTOR );

	int left_power;
	int right_power;
	int abs_turn_ratio = (turn_ratio < 0) ? -turn_ratio : turn_ratio;
	int abs_power = (power < 0) ? -power : power;

	if (abs_turn_ratio > 100) {
		abs_turn_ratio = 100;
	}
	if (abs_power > 100) {
		abs_power = 100;
	}
	left_power = abs_power;
	right_power = abs_power;
#if 0
	if (right_motor > left_motor) {
		turn_ratio = turn_ratio * (-1);
	}
#endif
	if (turn_ratio > 0) {
		right_power = (abs_power * (100 - abs_turn_ratio))  / 100 ;
	}
	else {
		left_power = (abs_power * (100 - abs_turn_ratio))  / 100 ;
	}
	if (power < 0) {
		left_power = left_power * (-1);
		right_power = right_power * (-1);
	}

	cLeftMotor_setPower(left_power);
	cRightMotor_setPower(right_power);
	return E_OK;
}


/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
