/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tMotor_template.c => src/tMotor.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * attr access macro #_CAAM_#
 * port             int32_t          ATTR_port       
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tMotor_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eMotor
 * entry port: eMotor
 * signature:  sMotor
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eMotor_setPower
 * name:         eMotor_setPower
 * global_name:  tMotor_eMotor_setPower
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eMotor_setPower(CELLIDX idx, int power)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	return ev3_motor_set_power(ATTR_port, power);
}

/* #[<ENTRY_FUNC>]# eMotor_initializePort
 * name:         eMotor_initializePort
 * global_name:  tMotor_eMotor_initializePort
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eMotor_initializePort(CELLIDX idx, int32_t type)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */
		return ev3_motor_config(ATTR_port,type);
	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
