/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tTouchSensor_template.c => src/tTouchSensor.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * attr access macro #_CAAM_#
 * port             int32_t          ATTR_port       
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tTouchSensor_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eTouchSensor
 * entry port: eTouchSensor
 * signature:  sTouchSensor
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eTouchSensor_isPressed
 * name:         eTouchSensor_isPressed
 * global_name:  tTouchSensor_eTouchSensor_isPressed
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
bool_t
eTouchSensor_isPressed(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */
	return ev3_touch_sensor_is_pressed(ATTR_port);
	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eTouchSensor_initializePort
 * name:         eTouchSensor_initializePort
 * global_name:  tTouchSensor_eTouchSensor_initializePort
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eTouchSensor_initializePort(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	return ev3_sensor_config(ATTR_port,TOUCH_SENSOR);
	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
