/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tUltrasonicSensor_template.c => src/tUltrasonicSensor.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * attr access macro #_CAAM_#
 * port             int32_t          ATTR_port       
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tUltrasonicSensor_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eUltrasonicSensor
 * entry port: eUltrasonicSensor
 * signature:  sUltrasonicSensor
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eUltrasonicSensor_getDistance
 * name:         eUltrasonicSensor_getDistance
 * global_name:  tUltrasonicSensor_eUltrasonicSensor_getDistance
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
int16_t
eUltrasonicSensor_getDistance(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */
	return ev3_ultrasonic_sensor_get_distance(ATTR_port);
	/* Put statements here #_TEFB_# */

}

/* #[<ENTRY_FUNC>]# eUltrasonicSensor_initializePort
 * name:         eUltrasonicSensor_initializePort
 * global_name:  tUltrasonicSensor_eUltrasonicSensor_initializePort
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eUltrasonicSensor_initializePort(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */
	return ev3_sensor_config(ATTR_port,ULTRASONIC_SENSOR);
	/* Put statements here #_TEFB_# */

}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
