/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tControlMain_template.c => src/tControlMain.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port: cControlMotors signature: sControlMotors context:task
 *   ER             cControlMotors_steer( int power, int turn_ratio );
 * call port: cColorSensor signature: sColorSensor context:task
 *   colorid_t      cColorSensor_getColor( );
 *   uint8_t        cColorSensor_getReflect( );
 *   uint8_t        cColorSensor_getAmbient( );
 *   void           cColorSensor_initializePort( );
 *   void           cColorSensor_getRGBRaw( uint16_t* r, uint16_t* g, uint16_t* b );
 * call port: cTouchSensor signature: sTouchSensor context:task
 *   bool_t         cTouchSensor_isPressed( );
 *   void           cTouchSensor_initializePort( );
 * call port: cUltrasonicSensor signature: sUltrasonicSensor context:task
 *   int16_t        cUltrasonicSensor_getDistance( );
 *   void           cUltrasonicSensor_initializePort( );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tControlMain_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eBody
 * entry port: eBody
 * signature:  sTaskBody
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eBody_main
 * name:         eBody_main
 * global_name:  tControlMain_eBody_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eBody_main(CELLIDX idx)
{
	CELLCB	*p_cellcb;
	if (VALID_IDX(idx)) {
		p_cellcb = GET_CELLCB(idx);
	}
	else {
		/* Write error processing code here */
	} /* end if VALID_IDX(idx) */

	/* Put statements here #_TEFB_# */
	cColorSensor_initializePort( );
	cTouchSensor_initializePort( );
	cUltrasonicSensor_initializePort( );
	

while(1) {

#define LIGHT_BRIGHT
#ifdef LIGHT_DARK

#define white 78
#define black 20
#else

#define white 100
#define black 50
#endif
        static float lasterror = 0, integral = 0;
        static float midpoint = (white - black) / 2 + black;
        {
            float error = midpoint - cColorSensor_getReflect();
#ifdef LIGHT_BRIGHT
            integral = error + integral * 0.01;
            float steer = 0.9 * error + 0.1 * integral + 1 * (error - lasterror);
#else
            integral = error + integral * 0.05;
            float steer = 0.7 * error + 0.1 * integral + 1 * (error - lasterror);
#endif
            cControlMotors_steer(10, steer);
            lasterror = error;
        }
        tslp_tsk(100000); /* 100msec */
	}
}


/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
